name: develop branch stuff

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check repo
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: dependencies installation
        run: |
          gem install bundler
          bundle install

      - name: rubocop install
        run: |
          gem install rubocop
          rubocop -a

      - name: bundler-audit
        run: |
          gem install bundler-audit
          bundle update loofah
          bundle audit update
          bundle audit check

      - name: rspec testing
        run: |
          gem install rspec
          rspec

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ruby-app:develop .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ruby-app:develop
