name: Develop CI Pipeline

on:
  push:
    branches:
      - develop
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3   
      
      - name: Ruby Setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
        
      - name: Install Dependencies
        run: bundle install

      - name: Rubocop Styling & Linting
        run: |
          gem install rubocop
          bundle exec rubocop
      
      - name: Dependency Vulnerabilities
        run: echo "Security Vulnerability checking handled by DependaBot!"

      - name: Unit Tests
        run: bundle exec rspec

      - name: Build Docker Image
        run: docker build -t $DOCKER_USERNAME/ruby-app:develop .

      - name: Push Docker Image
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push $DOCKER_USERNAME/ruby-app:develop